---
title: "HiC summary"
author: "Eric Fournier"
date: "`r Sys.Date()`"
output: html_document
---

```{r load_data, echo=FALSE}
source("scripts/load_hic_data.R")
hic_results = load_connection_data()
```

# Summary of analyzed promoters

Number of assessed genes: `r length(promoter_regions)`

## Differential expression across time:
```{r 2h_DE_summary, echo=FALSE}
time_order = c("DE-5m", "DE-10m", "DE-15m", "DE-20m", "DE-25m", "DE-0.5h", 
               "DE-1h", "DE-2h", "DE-3h", "DE-4h", "DE-5h", "DE-6h", "DE-7h",
               "DE-8h", "DE-10h", "DE-12h")
               
metrics_fun = function(time_point) {
    data.frame(Genes=c(sum(mcols(promoter_regions)[[time_point]] == "Up"),
                       sum(mcols(promoter_regions)[[time_point]] == "Down"),
                       sum(mcols(promoter_regions)[[time_point]] == "Stable")),
               Direction=c("Up", "Down", "Stable"),
               Time=time_point) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}

de_df = do.call(rbind, lapply(time_order, metrics_fun))
de_df$Time = factor(de_df$Time, levels=time_order)
ggplot(de_df[de_df$Direction != "Stable",], aes(x=Time, y=Genes, fill=Direction)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values=c(Up="#0ecc57", Down="red"))
```

```{r define_venn_plot_function, echo=FALSE}
    library(VennDiagram)

    venn_plot <- function(de_value, main) {
        is_de = promoter_regions$"2h" %in% de_value
        
        direct_indices = is_de & promoter_regions$EarlyBinding>4
        window_indices = is_de & promoter_regions$WindowBound
        contact_indices = is_de & promoter_regions$ContactBound
        
        gene_list = list(Direct=promoter_regions$ensembl_gene_id[direct_indices],
                         Window=promoter_regions$ensembl_gene_id[window_indices],
                         Contact=promoter_regions$ensembl_gene_id[contact_indices])
        
        unrepresented = sum(is_de & !direct_indices & !window_indices & !contact_indices)
        precent_unrepresented = sprintf(" (%2.0f%%) ", (unrepresented / sum(is_de)) * 100)
        main_title = paste0("Venn for genes in (", paste0(de_value, collapse=", "), ")")
        sub_title = paste0(unrepresented, precent_unrepresented, "have no binding at all.")
        
        grid.draw(venn.diagram(gene_list, filename=NULL,
                       fill=c("red", "yellow", "green"),
                       main=main_title,
                       sub=sub_title))    
    }
```

## GR-binding statuses
### GR-binding status for all genes:
```{r gr_binding_summary_all, echo=FALSE}
venn_plot(c("Stable", "Up", "Down"))
```

### GR-binding status for DE genes:
```{r gr_binding_summary_DE, echo=FALSE}
venn_plot(c("Up", "Down"))
```

### GR-binding status for Up genes:
```{r gr_binding_summary_Up, echo=FALSE}
venn_plot(c("Up"))
```

### GR-binding status for Down genes:
```{r gr_binding_summary_Down, echo=FALSE}
venn_plot(c("Down"))
```

```{r TAD_intra_vs_inter}
# Assess intra-TAD vs inter-TAD contacts.
f_a = anchors(input_hic, type="first")
s_a = anchors(input_hic, type="second")

f_tad = findOverlaps(f_a, all_hic$Ctrl$TAD)
s_tad = findOverlaps(s_a, all_hic$Ctrl$TAD)

tad_df = data.frame(f=rep(NA, length(f_a)), s=rep(NA, length(s_a)))
tad_df$f[queryHits(f_tad)] = subjectHits(f_tad)
tad_df$s[queryHits(s_tad)] = subjectHits(s_tad)
```

```{r decrease_in_gr_binding_over_time}
time_order = c("DE-5m", "DE-10m", "DE-15m", "DE-20m", "DE-25m", "DE-0.5h", 
               "DE-1h", "DE-2h", "DE-3h", "DE-4h", "DE-5h", "DE-6h", "DE-7h",
               "DE-8h", "DE-10h", "DE-12h")
direction_list = list(DE=c("Up", "Down"), Up="Up", Down="Down")

metrics_fun = function(y, time_point) {
    de_genes = mcols(promoter_regions)[[time_point]] %in% direction_list[[y]]
    direct_binding = promoter_regions$EarlyBinding > 0
    indirect_binding = promoter_regions$WindowBound |
                       promoter_regions$ContactBound 
    
    data.frame(DE=rep(sum(de_genes), 3),
               Bound=c(sum(de_genes & direct_binding),
                       sum(de_genes & !direct_binding & indirect_binding),
                       sum(de_genes & (direct_binding | indirect_binding))),
               BindingType=c("Direct", "Indirect", "Any"),
               Direction=y)
}

time_metrics = lapply(time_order, function(x) {
    metrics = lapply(names(direction_list), metrics_fun, time_point=x)
               
    res = do.call(rbind, metrics)
    res$Time = x
    
    res
})

data_df = do.call(rbind, time_metrics)
data_df$Time = factor(data_df$Time, levels=time_order)

ggplot(data_df, aes(x=Time, y=Bound/DE, color=Direction, group=Direction)) +
    geom_line() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    facet_wrap(BindingType~.)
```


```

```